import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Hero from "../components/Hero";
import Intro from "../components/Intro";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>{"Stichiboi | Creative Developer"}</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
            </Head>
            <main id={"home"} className={styles.main}>
                <Hero/>
                <Intro/>
            </main>
        </div>
    )
}

export default Home;
